### ISSUE TITLE
Properly parse and display markdown in chat

### ISSUE THREAD

**Issue by Josh-XT** [AGiXT/nextjs#61]
### Description

Properly parse and display markdown in chat
- ReactMarkdown does not seem to be doing the trick. 
- Expectation would be to have copyable code blocks if presented and to display Markdown properly like you would see from something like ChatGPT.

The example should have displayed the hello world example like this example below basically exactly as Github displays it with the ability to copy the code block and all:

```python
print("Hello, world!")
```

![image](https://github.com/AGiXT/nextjs/assets/102809327/ddbcfe73-4aeb-47b4-8f24-1cea8aea9e7e)

**Comment by greengeckowizard** [comment]
Let me know if this works #69 I threw it together quickly and not tested it. May need some tweaks possibly but other than that it should be good 👍 @Josh-XT

**Comment by Josh-XT** [comment]
![image-22](https://github.com/AGiXT/nextjs/assets/102809327/717f76ad-0ff4-41de-bae8-081b93980965)

Confirmed resolved. Thanks!
